region_list = {
    'Kangar': 'Region 1',
    'SPS': 'Region 1',
    'Sungai Siput': 'Region 1',
    'Alor Setar': 'Region 1',
    'Pendang': 'Region 1',
    'SPU': 'Region 1',
    'Seberang Perai': 'Region 1',
    'Gurun': 'Region 1',
    'Pekan Baru': 'Region 1',

    'Bangi': 'Region 2',
    'Cheras': 'Region 2',
    'Tanjung Karang': 'Region 2',
    'Sabak Bernam': 'Region 2',
    'Sungai Besar': 'Region 2',
    'Batang Berjuntai': 'Region 2',
    'Puchong': 'Region 2',
    'Kajang' : 'Region 2',
    'Jerantut': 'Region 2',
    'Kota Warisan': 'Region 2',

    'Meru': 'Region 3',
    'TTJ': 'Region 3',
    'Sri Rampai': 'Region 3',
    'Seremban': 'Region 3',
    'Rembau': 'Region 3',
    'Wangsa Maju': 'Region 3',
    'Kuala Pilah' : 'Region 3',
    'Andalas': 'Region 3',
    
    'BBU': 'Region 4',
    'Benut': 'Region 4',
    'Kota Tinggi': 'Region 4',
    'Kuala Sungai Baru': 'Region 4',
    'Pontian': 'Region 4',
    'Masjid Tanah': 'Region 4',
    'Johor Bharu': 'Region 4',
    'Taman Seri Setia': 'Region 4',
    'Batu Berendam': 'Region 4',

    'Kota Kinabalu': 'Region 5',
    'Tulip': 'Region 5',
    'Sandakan': 'Region 5',
    'Bangsar': 'Region 5',
    'Papar': 'Region 5',
    'Rawang': 'Region 5',
    'Antaragapi': 'Region 5',
    'Tamansari': 'Region 5'
}
